-- ============================================================
-- KAPRAO52 — COMPLETE DATABASE SETUP (IDEMPOTENT)
-- วิธีใช้: วาง SQL ทั้งหมดนี้ใน Supabase SQL Editor แล้วกด Run
-- สามารถรันซ้ำได้อย่างปลอดภัย (IF NOT EXISTS / OR REPLACE)
-- ============================================================

-- ============================================================
-- SECTION 1 : EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ============================================================
-- SECTION 2 : TABLE — profiles
-- เก็บข้อมูลผู้ใช้ทั้งหมด (LINE login + Guest/Anonymous)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id          uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    line_user_id    text UNIQUE,          -- LINE userId (เช่น Ua1b2c3d4...)
    display_name    text,                 -- ชื่อที่แสดง (จาก LINE หรือ 'Guest')
    picture_url     text,                 -- URL รูปโปรไฟล์จาก LINE
    avatar          text,                 -- URL รูป avatar ที่ custom เอง
    points          int  NOT NULL DEFAULT 0,
    total_orders    int  NOT NULL DEFAULT 0,
    tier            text NOT NULL DEFAULT 'MEMBER',  -- MEMBER | SILVER | GOLD | VIP
    is_admin        boolean NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Columns ที่อาจขาดในฐานข้อมูลเดิม (ALTER ... ADD COLUMN IF NOT EXISTS ปลอดภัย)
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS line_user_id   text UNIQUE,
    ADD COLUMN IF NOT EXISTS phone_number   text,
    ADD COLUMN IF NOT EXISTS display_name   text,
    ADD COLUMN IF NOT EXISTS picture_url    text,
    ADD COLUMN IF NOT EXISTS avatar         text,
    ADD COLUMN IF NOT EXISTS points         int  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_orders   int  NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tier           text NOT NULL DEFAULT 'MEMBER',
    ADD COLUMN IF NOT EXISTS is_admin       boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS created_at     timestamptz DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at     timestamptz DEFAULT now();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_profiles_line_user_id ON public.profiles(line_user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_phone_number ON public.profiles(phone_number);
CREATE INDEX IF NOT EXISTS idx_profiles_tier          ON public.profiles(tier);


-- ============================================================
-- SECTION 3 : TABLE — menu_items
-- ============================================================

CREATE TABLE IF NOT EXISTS public.menu_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text       NOT NULL,
    description     text,
    price           numeric    NOT NULL DEFAULT 0,
    category        text       NOT NULL DEFAULT 'others',
    image_url       text,
    requires_meat   boolean    NOT NULL DEFAULT true,
    is_recommended  boolean    NOT NULL DEFAULT false,
    is_available    boolean    NOT NULL DEFAULT true,
    spice_levels    int[],                        -- [1,2,3] ระดับความเผ็ด
    options         jsonb,                        -- extra options (เพิ่มไข่, ไม่เผ็ด ฯลฯ)
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Columns ที่อาจขาดในฐานข้อมูลเดิม (ครบทุก column)
ALTER TABLE public.menu_items
    ADD COLUMN IF NOT EXISTS description    text,
    ADD COLUMN IF NOT EXISTS image_url      text,
    ADD COLUMN IF NOT EXISTS requires_meat  boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS is_recommended boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS is_available   boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS spice_levels   int[],
    ADD COLUMN IF NOT EXISTS options        jsonb,
    ADD COLUMN IF NOT EXISTS created_at     timestamptz DEFAULT now();

-- Indexes (สร้างหลัง ALTER TABLE เพื่อให้แน่ใจว่า column มีอยู่แล้ว)
CREATE INDEX IF NOT EXISTS idx_menu_items_category       ON public.menu_items(category);
CREATE INDEX IF NOT EXISTS idx_menu_items_is_available   ON public.menu_items(is_available);
CREATE INDEX IF NOT EXISTS idx_menu_items_is_recommended ON public.menu_items(is_recommended);


-- ============================================================
-- SECTION 4 : TABLE — orders
-- ============================================================

CREATE TABLE IF NOT EXISTS public.orders (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             uuid REFERENCES auth.users(id),   -- Supabase Auth UID
    line_user_id        text,                             -- LINE userId (สำรอง)
    customer_name       text NOT NULL DEFAULT 'ลูกค้า',
    items               jsonb NOT NULL DEFAULT '[]'::jsonb,
    status              text NOT NULL DEFAULT 'placed',
    -- placed | confirmed | preparing | ready | delivered | cancelled
    total_price         numeric NOT NULL DEFAULT 0,
    subtotal_price      numeric NOT NULL DEFAULT 0,
    discount_amount     numeric NOT NULL DEFAULT 0,
    discount_code       text,
    points_redeemed     int NOT NULL DEFAULT 0,
    points_earned       int NOT NULL DEFAULT 0,
    payment_method      text NOT NULL DEFAULT 'cod',      -- cod | promptpay | other
    payment_status      text NOT NULL DEFAULT 'pending',  -- pending | paid | refunded
    notes               text,                             -- cancel reason / admin notes
    estimated_ready_time timestamptz,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- Columns ที่อาจขาดใน schema เดิม
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS customer_name       text DEFAULT 'ลูกค้า',
    ADD COLUMN IF NOT EXISTS line_user_id        text,
    ADD COLUMN IF NOT EXISTS subtotal_price      numeric DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount_amount     numeric DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount_code       text,
    ADD COLUMN IF NOT EXISTS points_redeemed     int DEFAULT 0,
    ADD COLUMN IF NOT EXISTS points_earned       int DEFAULT 0,
    ADD COLUMN IF NOT EXISTS payment_method      text DEFAULT 'cod',
    ADD COLUMN IF NOT EXISTS payment_status      text DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS notes               text,
    ADD COLUMN IF NOT EXISTS estimated_ready_time timestamptz,
    ADD COLUMN IF NOT EXISTS updated_at          timestamptz DEFAULT now();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orders_user_id     ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_line_uid    ON public.orders(line_user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status      ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at  ON public.orders(created_at DESC);


-- ============================================================
-- SECTION 5 : TABLE — point_logs
-- บันทึกประวัติการรับ/ใช้แต้มทุกครั้ง
-- ============================================================

CREATE TABLE IF NOT EXISTS public.point_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    action          text NOT NULL,    -- EARN | REDEEM | BONUS | ADJUST | EXPIRE
    amount          int  NOT NULL,    -- บวก = รับ, ลบ = ใช้
    order_id        bigint REFERENCES public.orders(id) ON DELETE SET NULL,
    note            text,
    balance_after   int  NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_point_logs_user_id   ON public.point_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_point_logs_order_id  ON public.point_logs(order_id);
CREATE INDEX IF NOT EXISTS idx_point_logs_created   ON public.point_logs(created_at DESC);


-- ============================================================
-- SECTION 6 : TABLE — lotto_pool
-- ที่เก็บเลขท้ายของ Order ID สำหรับลุ้นหวย
-- ============================================================

CREATE TABLE IF NOT EXISTS public.lotto_pool (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id     uuid   NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    number      text   NOT NULL,   -- เลขท้าย 2 หลักของ order_id
    draw_date   date   NOT NULL,   -- วันที่ออกรางวัล (1 หรือ 16 ของเดือน)
    is_winner   boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE(order_id)               -- 1 order = 1 ticket
);

CREATE INDEX IF NOT EXISTS idx_lotto_pool_user_id   ON public.lotto_pool(user_id);
CREATE INDEX IF NOT EXISTS idx_lotto_pool_draw_date ON public.lotto_pool(draw_date);

-- เพิ่ม column ที่อาจขาด
ALTER TABLE public.lotto_pool
    ADD COLUMN IF NOT EXISTS is_winner boolean NOT NULL DEFAULT false;


-- ============================================================
-- SECTION 7 : TABLE — lotto_results
-- ผลหวยรัฐบาลที่ admin บันทึก
-- ============================================================

CREATE TABLE IF NOT EXISTS public.lotto_results (
    draw_date   date   PRIMARY KEY,
    last2       text   NOT NULL,    -- เลขท้าย 2 ตัว
    first3      text[] NOT NULL DEFAULT '{}',  -- รางวัลเลขหน้า 3 ตัว
    created_at  timestamptz NOT NULL DEFAULT now()
);


-- ============================================================
-- SECTION 8 : TABLE — app_settings
-- ตั้งค่าระบบ เช่น shop_status เปิด/ปิด
-- ============================================================

CREATE TABLE IF NOT EXISTS public.app_settings (
    key     text PRIMARY KEY,
    value   jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- ค่าเริ่มต้น
INSERT INTO public.app_settings (key, value)
VALUES ('shop_status', '"open"'::jsonb)
ON CONFLICT (key) DO NOTHING;


-- ============================================================
-- SECTION 9 : ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Function helper สำหรับตรวจสอบความเป็น admin (หลีกเลี่ยง infinite recursion RLS)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    status boolean;
BEGIN
    SELECT is_admin INTO status FROM public.profiles WHERE id = auth.uid();
    RETURN COALESCE(status, false);
END;
$$;

-- Enable RLS on all tables
ALTER TABLE public.profiles     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.point_logs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotto_pool   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotto_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;


-- ── profiles ──────────────────────────────────────────────
-- ลบ policy เก่าและสร้างใหม่
DROP POLICY IF EXISTS "profiles_select_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_own"   ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_all"    ON public.profiles;
DROP POLICY IF EXISTS "profiles_admin_select_all" ON public.profiles;
DROP POLICY IF EXISTS "Users can view their own profile"   ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Anyone can view all profiles"       ON public.profiles;

-- ผู้ใช้ดูโปรไฟล์ตัวเอง
CREATE POLICY "profiles_select_own" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

-- Admin ดูลูกค้าทั้งหมด (ใช้ is_admin flag)
CREATE POLICY "profiles_admin_select_all" ON public.profiles
    FOR SELECT USING (public.is_admin());

-- ผู้ใช้ insert โปรไฟล์ตัวเอง (รองรับ Anonymous user ด้วย)
CREATE POLICY "profiles_insert_own" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

-- ผู้ใช้ update โปรไฟล์ตัวเอง
CREATE POLICY "profiles_update_own" ON public.profiles
    FOR UPDATE USING (auth.uid() = id);

-- service_role (trigger SECURITY DEFINER) ทำได้ทุกอย่าง — ทำโดยอัตโนมัติ


-- ── menu_items ────────────────────────────────────────────
DROP POLICY IF EXISTS "menu_public_select"    ON public.menu_items;
DROP POLICY IF EXISTS "menu_admin_all"        ON public.menu_items;
DROP POLICY IF EXISTS "menu_admin_insert"     ON public.menu_items;
DROP POLICY IF EXISTS "menu_admin_update"     ON public.menu_items;
DROP POLICY IF EXISTS "menu_admin_delete"     ON public.menu_items;
DROP POLICY IF EXISTS "Anyone can view menu"  ON public.menu_items;

-- ลูกค้าทุกคนดูเมนูได้ (รวม anon)
CREATE POLICY "menu_public_select" ON public.menu_items
    FOR SELECT USING (true);

-- เฉพาะ admin จัดการเมนู
CREATE POLICY "menu_admin_insert" ON public.menu_items
    FOR INSERT WITH CHECK (public.is_admin());
CREATE POLICY "menu_admin_update" ON public.menu_items
    FOR UPDATE USING (public.is_admin());
CREATE POLICY "menu_admin_delete" ON public.menu_items
    FOR DELETE USING (public.is_admin());


-- ── orders ────────────────────────────────────────────────
DROP POLICY IF EXISTS "orders_insert_own"       ON public.orders;
DROP POLICY IF EXISTS "orders_select_own"       ON public.orders;
DROP POLICY IF EXISTS "orders_update_own"       ON public.orders;
DROP POLICY IF EXISTS "orders_admin_all"        ON public.orders;
DROP POLICY IF EXISTS "orders_insert_any_auth"  ON public.orders;
DROP POLICY IF EXISTS "orders_admin_select_all" ON public.orders;
DROP POLICY IF EXISTS "orders_admin_update"     ON public.orders;
DROP POLICY IF EXISTS "orders_admin_delete"     ON public.orders;
DROP POLICY IF EXISTS "Users can insert their own orders" ON public.orders;
DROP POLICY IF EXISTS "Users can view their own orders"  ON public.orders;
DROP POLICY IF EXISTS "Users can update their own orders" ON public.orders;

-- ทุก authenticated/anon user สั่งอาหารได้
CREATE POLICY "orders_insert_any_auth" ON public.orders
    FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));

-- ผู้ใช้ดูออเดอร์ตัวเอง
CREATE POLICY "orders_select_own" ON public.orders
    FOR SELECT USING (auth.uid() = user_id);

-- admin ดูออเดอร์ทั้งหมด
CREATE POLICY "orders_admin_select_all" ON public.orders
    FOR SELECT USING (public.is_admin());

-- admin อัพเดต/ลบออเดอร์ได้
CREATE POLICY "orders_admin_update" ON public.orders
    FOR UPDATE USING (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "orders_admin_delete" ON public.orders
    FOR DELETE USING (public.is_admin());


-- ── point_logs ────────────────────────────────────────────
DROP POLICY IF EXISTS "point_logs_select_own"  ON public.point_logs;
DROP POLICY IF EXISTS "point_logs_insert"      ON public.point_logs;
DROP POLICY IF EXISTS "point_logs_admin_select" ON public.point_logs;
DROP POLICY IF EXISTS "point_logs_insert_auth" ON public.point_logs;
DROP POLICY IF EXISTS "Users can view their own point logs" ON public.point_logs;
DROP POLICY IF EXISTS "Authenticated users can insert point logs" ON public.point_logs;

-- ผู้ใช้ดู log แต้มตัวเอง
CREATE POLICY "point_logs_select_own" ON public.point_logs
    FOR SELECT USING (auth.uid() = user_id);

-- admin ดู log ทุกคน
CREATE POLICY "point_logs_admin_select" ON public.point_logs
    FOR SELECT USING (public.is_admin());

-- authenticated users insert ได้ (trigger SECURITY DEFINER ที่ใช้บ่อย)
CREATE POLICY "point_logs_insert_auth" ON public.point_logs
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- ── lotto_pool ────────────────────────────────────────────
DROP POLICY IF EXISTS "lotto_select_own"        ON public.lotto_pool;
DROP POLICY IF EXISTS "lotto_insert_own"        ON public.lotto_pool;
DROP POLICY IF EXISTS "lotto_admin_select"      ON public.lotto_pool;
DROP POLICY IF EXISTS "lotto_insert_auth"       ON public.lotto_pool;
DROP POLICY IF EXISTS "Anyone can view lotto pool" ON public.lotto_pool;
DROP POLICY IF EXISTS "Users can insert their own lotto" ON public.lotto_pool;
DROP POLICY IF EXISTS "Users can view their own lotto numbers" ON public.lotto_pool;

CREATE POLICY "lotto_select_own" ON public.lotto_pool
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "lotto_admin_select" ON public.lotto_pool
    FOR SELECT USING (public.is_admin());

-- trigger (SECURITY DEFINER) จะ insert อัตโนมัติ
CREATE POLICY "lotto_insert_auth" ON public.lotto_pool
    FOR INSERT WITH CHECK (auth.role() IN ('authenticated', 'anon'));


-- ── lotto_results ─────────────────────────────────────────
DROP POLICY IF EXISTS "Anyone can view lotto results" ON public.lotto_results;
DROP POLICY IF EXISTS "lotto_results_public_select" ON public.lotto_results;
DROP POLICY IF EXISTS "lotto_results_admin_insert" ON public.lotto_results;

CREATE POLICY "lotto_results_public_select" ON public.lotto_results
    FOR SELECT USING (true);

CREATE POLICY "lotto_results_admin_insert" ON public.lotto_results
    FOR INSERT WITH CHECK (public.is_admin());


-- ── app_settings ──────────────────────────────────────────
DROP POLICY IF EXISTS "app_settings_public_select" ON public.app_settings;
DROP POLICY IF EXISTS "app_settings_admin_update"  ON public.app_settings;

CREATE POLICY "app_settings_public_select" ON public.app_settings
    FOR SELECT USING (true);

CREATE POLICY "app_settings_admin_update" ON public.app_settings
    FOR ALL USING (public.is_admin());


-- ============================================================
-- SECTION 10 : TRIGGER — auto-create profile on signup
-- รองรับทั้ง LINE login + Guest (Anonymous)
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, display_name, points, total_orders, tier, updated_at)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', 'ลูกค้า'),
        0,
        0,
        'MEMBER',
        now()
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ============================================================
-- SECTION 11 : TRIGGER — handle_order_placed
-- เมื่อมีออเดอร์ใหม่ → อัพเดตแต้ม + นับออเดอร์ + สร้างตั๋วหวย
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_order_placed()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    earned_points   int := 0;
    lotto_num       text;
    next_draw       date;
    current_points  int;
    day_now         int;
    month_now       int;
    year_now        int;
BEGIN
    -- รันเฉพาะเมื่อ status = 'placed' (INSERT ใหม่ หรือ UPDATE มาจาก status อื่น)
    IF NEW.status = 'placed' AND (TG_OP = 'INSERT' OR OLD.status != 'placed') THEN

        -- ─── 1. คำนวณแต้มที่ได้รับ ─────────────────────────────
        IF NEW.points_earned IS NOT NULL AND NEW.points_earned > 0 THEN
            earned_points := NEW.points_earned;
        ELSE
            -- 1 แต้มต่อ 10 บาท
            earned_points := FLOOR(COALESCE(NEW.total_price, 0) / 10);
        END IF;

        -- ─── 2. อัพเดต profiles (เฉพาะ user ที่ล็อกอิน) ────────
        IF NEW.user_id IS NOT NULL THEN

            -- 2a. หักแต้มที่ใช้แลก (ถ้ามี)
            IF COALESCE(NEW.points_redeemed, 0) > 0 THEN
                UPDATE public.profiles
                SET points      = GREATEST(0, points - NEW.points_redeemed),
                    updated_at  = now()
                WHERE id = NEW.user_id;

                SELECT points INTO current_points
                FROM public.profiles WHERE id = NEW.user_id;

                INSERT INTO public.point_logs
                    (user_id, action, amount, order_id, note, balance_after)
                VALUES
                    (NEW.user_id, 'REDEEM', -NEW.points_redeemed, NEW.id,
                     'แลกส่วนลด Order #' || NEW.id, COALESCE(current_points, 0));
            END IF;

            -- 2b. เพิ่มแต้มที่ได้ + นับออเดอร์
            UPDATE public.profiles
            SET points          = points + earned_points,
                total_orders    = total_orders + 1,
                -- อัพเดต tier อัตโนมัติ
                tier = CASE
                    WHEN (points + earned_points) >= 2000 THEN 'VIP'
                    WHEN (points + earned_points) >= 1000 THEN 'GOLD'
                    WHEN (points + earned_points) >= 500  THEN 'SILVER'
                    ELSE 'MEMBER'
                END,
                updated_at = now()
            WHERE id = NEW.user_id;

            IF earned_points > 0 THEN
                SELECT points INTO current_points
                FROM public.profiles WHERE id = NEW.user_id;

                INSERT INTO public.point_logs
                    (user_id, action, amount, order_id, note, balance_after)
                VALUES
                    (NEW.user_id, 'EARN', earned_points, NEW.id,
                     'สั่งอาหาร Order #' || NEW.id, COALESCE(current_points, 0));
            END IF;

            -- ─── 3. สร้างตั๋วหวย ──────────────────────────────────
            lotto_num := LPAD(RIGHT(NEW.id::text, 2), 2, '0');

            day_now   := EXTRACT(DAY   FROM now())::int;
            month_now := EXTRACT(MONTH FROM now())::int;
            year_now  := EXTRACT(YEAR  FROM now())::int;

            IF    day_now >= 1  AND day_now < 16 THEN
                next_draw := make_date(year_now, month_now, 16);
            ELSIF day_now >= 16 THEN
                -- วันที่ 1 ของเดือนถัดไป
                next_draw := (date_trunc('month', now()) + interval '1 month')::date;
            ELSE
                next_draw := make_date(year_now, month_now, 1);
            END IF;

            INSERT INTO public.lotto_pool (order_id, user_id, number, draw_date)
            VALUES (NEW.id, NEW.user_id, lotto_num, next_draw)
            ON CONFLICT (order_id) DO NOTHING;

        END IF; -- end user_id IS NOT NULL
    END IF; -- end status = 'placed'

    RETURN NEW;
END;
$$;

-- ลบ trigger เก่าทั้งหมดและสร้างใหม่
DROP TRIGGER IF EXISTS on_order_placed        ON public.orders;
DROP TRIGGER IF EXISTS on_order_insert_placed ON public.orders;
DROP TRIGGER IF EXISTS on_order_update_placed ON public.orders;

-- trigger สำหรับ INSERT (ออเดอร์ใหม่ที่สถานะ placed ทันที)
CREATE TRIGGER on_order_insert_placed
AFTER INSERT ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.handle_order_placed();

-- trigger สำหรับ UPDATE (admin เปลี่ยน status → placed)
CREATE TRIGGER on_order_update_placed
AFTER UPDATE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.handle_order_placed();


-- ============================================================
-- SECTION 12 : RPC — update_user_points
-- ใช้จาก client เมื่อ admin ปรับแต้มด้วยมือ
-- ============================================================

-- ลบทุก signature เก่าของ function นี้ (CASCADE ลบทีละตามไป)
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int);
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int, bigint);
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int, text);
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int, text, text);
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int, text, text, bigint);
DROP FUNCTION IF EXISTS public.update_user_points(uuid, int, bigint, text);

CREATE OR REPLACE FUNCTION public.update_user_points(
    p_user_id   uuid,
    p_amount    int,
    p_action    text DEFAULT 'ADJUST',
    p_note      text DEFAULT NULL,
    p_order_id  bigint DEFAULT NULL
)
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_balance int;
BEGIN
    -- อัพเดตแต้ม (ป้องกันไม่ให้ติดลบ)
    UPDATE public.profiles
    SET points      = GREATEST(0, points + p_amount),
        tier = CASE
            WHEN GREATEST(0, points + p_amount) >= 2000 THEN 'VIP'
            WHEN GREATEST(0, points + p_amount) >= 1000 THEN 'GOLD'
            WHEN GREATEST(0, points + p_amount) >= 500  THEN 'SILVER'
            ELSE 'MEMBER'
        END,
        updated_at  = now()
    WHERE id = p_user_id
    RETURNING points INTO new_balance;

    -- บันทึก log
    INSERT INTO public.point_logs (user_id, action, amount, order_id, note, balance_after)
    VALUES (p_user_id, p_action, p_amount, p_order_id,
            COALESCE(p_note, p_action || ' ' || p_amount || ' points'),
            COALESCE(new_balance, 0));

    RETURN COALESCE(new_balance, 0);
END;
$$;

-- ระบุ argument list ให้ชัดเจน เพื่อหลีกปัญหา ambiguous
GRANT EXECUTE ON FUNCTION public.update_user_points(uuid, int, text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_points(uuid, int, text, text, bigint) TO anon;


-- ============================================================
-- SECTION 13 : RPC — get_or_create_profile_by_line_id
-- ใช้สำหรับ LINE login flow — หา profile จาก line_user_id
-- ถ้ายังไม่มี → สร้าง (UPSERT-safe)
-- ============================================================

-- ลบทุก signature เก่าของ function นี้
DROP FUNCTION IF EXISTS public.get_or_create_profile_by_line_id(uuid, text, text);
DROP FUNCTION IF EXISTS public.get_or_create_profile_by_line_id(uuid, text, text, text);

CREATE OR REPLACE FUNCTION public.get_or_create_profile_by_line_id(
    p_supabase_uid  uuid,
    p_line_user_id  text,
    p_display_name  text,
    p_picture_url   text DEFAULT NULL
)
RETURNS public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    result public.profiles;
BEGIN
    -- Upsert: สร้างถ้าไม่มี, อัพเดตถ้ามีแล้ว
    INSERT INTO public.profiles
        (id, line_user_id, display_name, picture_url, points, total_orders, tier, updated_at)
    VALUES
        (p_supabase_uid, p_line_user_id, p_display_name, p_picture_url, 0, 0, 'MEMBER', now())
    ON CONFLICT (id) DO UPDATE
        SET line_user_id  = EXCLUDED.line_user_id,
            display_name  = COALESCE(EXCLUDED.display_name, profiles.display_name),
            picture_url   = COALESCE(EXCLUDED.picture_url,  profiles.picture_url),
            updated_at    = now()
    RETURNING * INTO result;

    RETURN result;
END;
$$;

-- ระบุ argument list ให้ชัดเจน
GRANT EXECUTE ON FUNCTION public.get_or_create_profile_by_line_id(uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_or_create_profile_by_line_id(uuid, text, text, text) TO anon;


-- ============================================================
-- SECTION 14 : SEED DATA — menu_items (เมนูเริ่มต้น)
-- รัน INSERT ... ON CONFLICT DO NOTHING ปลอดภัย ไม่ทับข้อมูลเดิม
-- ============================================================

INSERT INTO public.menu_items (id, name, description, price, category, image_url, is_recommended, is_available, requires_meat)
OVERRIDING SYSTEM VALUE
VALUES
    -- ══════════════════════════════════════════════
    -- 🌶️ หมวด 1: กะเพรา (kaprao)
    -- ══════════════════════════════════════════════
    (1,  'ผัดกะเพรา',             'ผัดกะเพราพริกแห้งสูตรเด็ด รสจัดจ้าน หอมใบกะเพราแท้ (เลือกเนื้อสัตว์ได้)', 55,  'kaprao', '/images/kaprao-moo-sap.jpg',      true,  true, true),
    (2,  'กะเพราหมูกรอบ',          'หมูกรอบชิ้นใหญ่ กรอบนอกนุ่มใน คั่วกะเพราพริกแห้งสูตรเด็ด',             70,  'kaprao', '/images/kaprao-moo-krob.jpg',     true,  true, false),
    (3,  'กะเพราไข่เยี่ยวม้า',       'ไข่เยี่ยวม้าทอดกรอบ ผัดกะเพราพริกแห้งร่วมกับเนื้อสัตว์ที่คุณเลือก',     75,  'kaprao', '/images/kaprao-kai-yiao-ma.jpg',  true,  true, true),
    (4,  'กะเพรากุ้ง',             'กุ้งสดตัวโตเนื้อเด้ง ผัดกะเพราพริกสดจัดจ้านกลิ่นหอมฟุ้ง',               85,  'kaprao', '/images/kaprao-kung.jpg',         true,  true, false),

    -- ══════════════════════════════════════════════
    -- 🧄 หมวด 2: ผัดกระเทียม (garlic)
    -- ══════════════════════════════════════════════
    (5,  'ผัดกระเทียม',           'ผัดกระเทียมพริกไทยสูตรเข้มข้น โรยกระเทียมเจียวกรอบหอมฟุ้ง (เลือกเนื้อสัตว์ได้)', 55, 'garlic', '/images/moo-sap-kra-thiam.jpg',  true,  true, true),
    (6,  'หมูกรอบผัดกระเทียม',     'หมูกรอบทอดกรอบ ผัดกระเทียมพริกไทยสูตรพิเศษ',                          70, 'garlic', '/images/san-ko-kra-thiam.jpg',   false, true, false),
    (7,  'กุ้งผัดกระเทียม',        'กุ้งสดตัวใหญ่ทอดกรอบ คลุกเคล้ากระเทียมพริกไทยสูตรลับ',                85, 'garlic', '/images/kung-kra-thiam.jpg',     true,  true, false),

    -- ══════════════════════════════════════════════
    -- 🥘 หมวด 3: ผัดพริกแกง (curry)
    -- ══════════════════════════════════════════════
    (8,  'ผัดพริกแกง',           'เครื่องแกงใต้แท้ผัดกะทิหอมๆ ใส่ถั่วฝักยาวกรอบอร่อย (เลือกเนื้อสัตว์ได้)', 55, 'curry',  '/images/prik-kang-moo-chin.jpg', true,  true, true),
    (9,  'พริกแกงหมูกรอบ',        'พริกแกงใต้เข้มข้น ผัดคลุกเคล้าหมูกรอบชิ้นโต',                         70, 'curry',  '/images/prik-kang-moo-chin.jpg', false, true, false),

    -- ══════════════════════════════════════════════
    -- 🎋 หมวด 4: ผัดหน่อไม้ (bamboo)
    -- ══════════════════════════════════════════════
    (10, 'ผัดหน่อไม้ดอง',         'หน่อไม้ดองกรุบกรอบ ผัดพริกสดจัดจ้านเข้มข้น (เลือกเนื้อสัตว์ได้)',        55, 'bamboo', '/images/kaprao-nor-mai.jpg',    true,  true, true),
    (11, 'หน่อไม้ดองผัดหมูกรอบ',   'หน่อไม้ดองผัดพริกสดใส่หมูกรอบ เผ็ดเปรี้ยวกรุบกรอบลงตัว',               70, 'bamboo', '/images/kaprao-nor-mai.jpg',    false, true, false),

    -- ══════════════════════════════════════════════
    -- 🍜 หมวด 5: ก๋วยเตี๋ยว & เส้น (noodle)
    -- ══════════════════════════════════════════════
    (12, 'มาม่าผัดกะเพรา',        'เส้นมาม่าเหนียวนุ่ม ผัดกะเพราพริกแห้งรสจัดจ้าน (เลือกเนื้อสัตว์ได้)',      55, 'noodle', '/images/mama-pad-kaprao.jpg',    true,  true, true),
    (13, 'มาม่าผัดกะเพราหมูกรอบ',  'มาม่าผัดกะเพราใส่หมูกรอบเน้นๆ อร่อยเต็มคำ',                           70, 'noodle', '/images/mama-pad-kaprao.jpg',    false, true, false),

    -- ══════════════════════════════════════════════
    -- 🍚 หมวด 6: อื่นๆ (others)
    -- ══════════════════════════════════════════════
    (14, 'ข้าวผัด',              'ข้าวผัดโบราณหอมกลิ่นกระทะ ข้าวเรียงเม็ดสวย ใส่ไข่และผัก (เลือกเนื้อสัตว์ได้)', 55, 'others', '/images/khao-pad-moo-chin.jpg',  true,  true, true)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- SECTION 15 : BACKFILL — สร้าง profile สำหรับ user เดิม
-- ที่ signup ไปแล้วก่อนที่ trigger จะถูกสร้าง
-- ============================================================

INSERT INTO public.profiles (id, display_name, points, total_orders, tier, updated_at)
SELECT
    u.id,
    COALESCE(u.raw_user_meta_data->>'full_name', u.raw_user_meta_data->>'name', 'ลูกค้า'),
    0,
    0,
    'MEMBER',
    now()
FROM auth.users u
WHERE NOT EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = u.id
)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- SECTION 16 : GUEST IDENTITIES & LOTTO TICKETS v2.0
-- ============================================================

-- Columns ที่อาจขาดใน orders
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS guest_id         UUID,
    ADD COLUMN IF NOT EXISTS queue_type       TEXT,
    ADD COLUMN IF NOT EXISTS queue_number     INT,
    ADD COLUMN IF NOT EXISTS queue_display    TEXT,
    ADD COLUMN IF NOT EXISTS estimated_minutes INT,
    ADD COLUMN IF NOT EXISTS scheduled_for    TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS is_preorder     BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS guest_synced    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS guest_synced_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS tracking_token   TEXT;

CREATE INDEX IF NOT EXISTS idx_orders_guest_id ON public.orders(guest_id) WHERE guest_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_queue    ON public.orders(queue_type, queue_number) WHERE queue_type IS NOT NULL;

-- Table: guest_identities
CREATE TABLE IF NOT EXISTS public.guest_identities (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fingerprint    TEXT UNIQUE,
    display_name   TEXT NOT NULL DEFAULT 'Guest',
    metadata       JSONB DEFAULT '{}',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guest_identities_fingerprint ON public.guest_identities(fingerprint) WHERE fingerprint IS NOT NULL;

-- Table: lotto_tickets
CREATE TABLE IF NOT EXISTS public.lotto_tickets (
    id                BIGSERIAL PRIMARY KEY,
    order_id          BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id           UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    guest_id          UUID REFERENCES public.guest_identities(id) ON DELETE CASCADE,
    number            TEXT NOT NULL,
    number_type       TEXT DEFAULT 'auto',
    source            TEXT DEFAULT 'order_free',
    purchase_price    INT DEFAULT 0,
    draw_date         DATE NOT NULL,
    status            TEXT DEFAULT 'active',
    prize_type        TEXT,
    prize_amount      INT DEFAULT 0,
    prize_claimed     BOOLEAN DEFAULT FALSE,
    prize_claimed_at  TIMESTAMPTZ,
    notification_sent BOOLEAN DEFAULT FALSE,
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT valid_number CHECK (char_length(number) BETWEEN 2 AND 6),
    CONSTRAINT valid_number_type CHECK (number_type IN ('auto', 'manual', 'vip')),
    CONSTRAINT valid_source CHECK (source IN ('order_free', 'points_purchase', 'bonus', 'streak', 'vip_monthly'))
);

CREATE INDEX IF NOT EXISTS idx_lotto_tickets_user  ON public.lotto_tickets(user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lotto_tickets_guest ON public.lotto_tickets(guest_id) WHERE guest_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_lotto_tickets_draw  ON public.lotto_tickets(draw_date);
CREATE INDEX IF NOT EXISTS idx_lotto_tickets_order ON public.lotto_tickets(order_id);

-- RPC 1: generate_queue_number
CREATE OR REPLACE FUNCTION generate_queue_number(
    p_delivery_method TEXT,
    p_is_preorder BOOLEAN DEFAULT FALSE
)
RETURNS TABLE (out_queue_type TEXT, out_queue_number INT, out_queue_display TEXT) AS $$
DECLARE
    v_prefix TEXT;
    v_next_number INT;
BEGIN
    IF p_is_preorder THEN
        v_prefix := 'D';
    ELSIF p_delivery_method = 'workplace' THEN
        v_prefix := 'A';
    ELSIF p_delivery_method = 'village' THEN
        v_prefix := 'B';
    ELSE
        v_prefix := 'C';
    END IF;
    
    SELECT COALESCE(MAX(queue_number), 0) + 1 INTO v_next_number
    FROM orders
    WHERE queue_type = v_prefix
      AND DATE(created_at) = CURRENT_DATE;
    
    RETURN QUERY SELECT v_prefix, v_next_number, v_prefix || LPAD(v_next_number::TEXT, 3, '0');
END;
$$ LANGUAGE plpgsql;

-- RPC 2: get_queue_status
CREATE OR REPLACE FUNCTION get_queue_status(p_order_id BIGINT)
RETURNS JSON AS $$
DECLARE
    v_order RECORD;
    v_orders_ahead INT;
    v_estimated_minutes INT;
BEGIN
    SELECT * INTO v_order FROM orders WHERE id = p_order_id;
    IF NOT FOUND THEN
        RETURN json_build_object('error', 'Order not found');
    END IF;
    
    SELECT COUNT(*) INTO v_orders_ahead
    FROM orders
    WHERE queue_type = v_order.queue_type
      AND queue_number < v_order.queue_number
      AND DATE(created_at) = DATE(v_order.created_at)
      AND status NOT IN ('delivered', 'cancelled');
    
    v_estimated_minutes := v_orders_ahead * 5 + 10;
    
    RETURN json_build_object(
        'queue_display', v_order.queue_display,
        'queue_type', v_order.queue_type,
        'orders_ahead', v_orders_ahead,
        'estimated_minutes', v_estimated_minutes,
        'status', v_order.status
    );
END;
$$ LANGUAGE plpgsql;

-- RPC 3: sync_guest_to_member
CREATE OR REPLACE FUNCTION sync_guest_to_member(
    p_guest_id UUID,
    p_user_id UUID
)
RETURNS JSON AS $$
DECLARE
    v_points_earned INT := 0;
    v_tickets_count INT := 0;
    v_orders_count INT := 0;
BEGIN
    UPDATE orders
    SET user_id = p_user_id, guest_synced = TRUE, guest_synced_at = NOW(), updated_at = NOW()
    WHERE guest_id = p_guest_id AND (guest_synced = FALSE OR guest_synced IS NULL);
    GET DIAGNOSTICS v_orders_count = ROW_COUNT;
    
    SELECT COALESCE(SUM(points_earned), 0) INTO v_points_earned
    FROM orders WHERE guest_id = p_guest_id;
    
    UPDATE lotto_tickets
    SET user_id = p_user_id, guest_id = NULL, updated_at = NOW()
    WHERE guest_id = p_guest_id;
    GET DIAGNOSTICS v_tickets_count = ROW_COUNT;
    
    IF v_points_earned > 0 THEN
        UPDATE profiles
        SET points = COALESCE(points, 0) + v_points_earned,
            total_orders = COALESCE(total_orders, 0) + v_orders_count,
            updated_at = NOW()
        WHERE id = p_user_id;
        
        INSERT INTO point_logs (user_id, action, amount, note, balance_after)
        SELECT p_user_id, 'EARN', v_points_earned,
               'Points from ' || v_orders_count || ' guest orders', points
        FROM profiles WHERE id = p_user_id;
    END IF;
    
    UPDATE guest_identities
    SET metadata = jsonb_set(COALESCE(metadata, '{}'), '{synced_to}', to_jsonb(p_user_id::TEXT))
    WHERE id = p_guest_id;
    
    RETURN json_build_object(
        'success', TRUE,
        'orders_synced', v_orders_count,
        'points_added', v_points_earned,
        'tickets_transferred', v_tickets_count
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================================
-- SECTION 17 : GRANT สิทธิ์พื้นฐาน
-- ============================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT                ON public.menu_items       TO anon, authenticated;
GRANT SELECT                ON public.app_settings     TO anon, authenticated;
GRANT SELECT                ON public.lotto_results    TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE ON public.profiles       TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.guest_identities TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.lotto_tickets   TO anon, authenticated;
GRANT SELECT, INSERT        ON public.orders          TO anon, authenticated;
GRANT UPDATE                ON public.orders          TO authenticated;
GRANT SELECT, INSERT        ON public.point_logs      TO authenticated;
GRANT SELECT, INSERT        ON public.lotto_pool      TO authenticated;

GRANT INSERT, UPDATE, DELETE ON public.menu_items     TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.app_settings    TO authenticated;
GRANT INSERT                ON public.lotto_results    TO authenticated;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;


-- ============================================================
-- DONE ✅
-- ทุก table, index, RLS policy, trigger, function, seed data
-- พร้อมใช้งานใน Kaprao52 App แล้ว
-- ============================================================

