-- ============================================================
-- KAPRAO52 — COMPLETE PRE-LAUNCH MIGRATION
-- รวมทุกฟีเจอร์ที่จำเป็นต้องใช้ก่อนเปิดร้านจริง
-- ============================================================

-- ============================================================
-- SECTION 1: SHOP CONFIGURATION TABLE (แทนที่ค่า Hardcoded)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.shop_config (
    key             text PRIMARY KEY,
    value           jsonb NOT NULL,
    description     text,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid REFERENCES auth.users(id)
);

-- Insert default shop config
INSERT INTO public.shop_config (key, value, description) VALUES
('contact', '{"phone": "0812345678", "line_id": "@kaprao52", "line_oa_id": "@772ysswn"}'::jsonb, 'ข้อมูลติดต่อร้าน'),
('shop_hours', '{"open": "08:00", "close": "17:00", "days_open": [1,2,3,4,5], "timezone": "Asia/Bangkok"}'::jsonb, 'เวลาเปิด-ปิดร้าน'),
('order_limits', '{"max_orders_per_slot": 20, "slot_duration_minutes": 30, "max_items_per_order": 50}'::jsonb, 'จำกัดจำนวนออเดอร์'),
('payment', '{"promptpay_number": "0812345678", "promptpay_name": "นายสมชาย ใจดี", "bank_accounts": []}'::jsonb, 'ข้อมูลการชำระเงิน')
ON CONFLICT (key) DO NOTHING;

-- Enable RLS
ALTER TABLE public.shop_config ENABLE ROW LEVEL SECURITY;

-- Policy: ทุกคนอ่านได้, แอดมินเท่านั้นที่แก้ไขได้
CREATE POLICY "shop_config_select_all" ON public.shop_config FOR SELECT USING (true);
CREATE POLICY "shop_config_update_admin" ON public.shop_config FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);
CREATE POLICY "shop_config_insert_admin" ON public.shop_config FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- ============================================================
-- SECTION 2: PAYMENT SYSTEM — SLIP VERIFICATION
-- ============================================================

-- Add columns to orders table for payment proof
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS payment_proof_url    text,
    ADD COLUMN IF NOT EXISTS payment_verified     boolean DEFAULT false,
    ADD COLUMN IF NOT EXISTS payment_verified_at  timestamptz,
    ADD COLUMN IF NOT EXISTS payment_verified_by  uuid REFERENCES auth.users(id),
    ADD COLUMN IF NOT EXISTS payment_slip_data    jsonb,
    ADD COLUMN IF NOT EXISTS payment_due_at       timestamptz;

-- ============================================================
-- SECTION 3: REVIEWS & RATINGS SYSTEM
-- ============================================================
CREATE TABLE IF NOT EXISTS public.reviews (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id         uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    menu_item_ids   bigint[] DEFAULT '{}',
    rating          int NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment         text,
    images          text[] DEFAULT '{}',
    would_recommend boolean,
    reply           text,
    replied_at      timestamptz,
    replied_by      uuid REFERENCES auth.users(id),
    is_approved     boolean DEFAULT true,
    helpful_count   int DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Review helpful votes (prevent duplicate votes)
CREATE TABLE IF NOT EXISTS public.review_votes (
    review_id       bigint REFERENCES public.reviews(id) ON DELETE CASCADE,
    user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (review_id, user_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_reviews_order_id ON public.reviews(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_menu_item_ids ON public.reviews USING gin(menu_item_ids);
CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON public.reviews(created_at DESC);

-- RLS Policies
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "reviews_select_all" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "reviews_insert_own" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "reviews_update_own" ON public.reviews FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "reviews_delete_admin" ON public.reviews FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- ============================================================
-- SECTION 4: REAL COUPON/DISCOUNT SYSTEM
-- ============================================================
CREATE TABLE IF NOT EXISTS public.coupons (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL UNIQUE,
    name            text NOT NULL,
    description     text,
    discount_type   text NOT NULL CHECK (discount_type IN ('fixed', 'percentage', 'free_delivery')),
    discount_value  numeric NOT NULL DEFAULT 0,
    min_order_amount numeric DEFAULT 0,
    max_discount    numeric,
    usage_limit     int,
    usage_count     int DEFAULT 0,
    per_user_limit  int DEFAULT 1,
    applicable_items bigint[],
    excluded_items   bigint[],
    starts_at       timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz,
    is_active       boolean DEFAULT true,
    created_by      uuid REFERENCES auth.users(id),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Track coupon usage per user
CREATE TABLE IF NOT EXISTS public.coupon_usages (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id       bigint NOT NULL REFERENCES public.coupons(id),
    user_id         uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    order_id        bigint REFERENCES public.orders(id) ON DELETE SET NULL,
    discount_amount numeric NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons(code);
CREATE INDEX IF NOT EXISTS idx_coupons_active ON public.coupons(is_active, starts_at, expires_at);
CREATE INDEX IF NOT EXISTS idx_coupon_usages_user ON public.coupon_usages(user_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usages_coupon ON public.coupon_usages(coupon_id);

-- RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "coupons_select_active" ON public.coupons FOR SELECT USING (is_active = true AND (expires_at IS NULL OR expires_at > now()));
CREATE POLICY "coupons_admin_all" ON public.coupons FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

CREATE POLICY "coupon_usages_select_own" ON public.coupon_usages FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "coupon_usages_insert_own" ON public.coupon_usages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- SECTION 5: ORDER LIMITS & QUEUE MANAGEMENT
-- ============================================================
CREATE TABLE IF NOT EXISTS public.order_slots (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date       date NOT NULL,
    slot_time       time NOT NULL,
    delivery_method text NOT NULL CHECK (delivery_method IN ('workplace', 'village')),
    max_orders      int NOT NULL DEFAULT 20,
    current_orders  int NOT NULL DEFAULT 0,
    is_locked       boolean DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE(slot_date, slot_time, delivery_method)
);

-- Pre-generate slots (function)
CREATE OR REPLACE FUNCTION generate_order_slots(
    p_date date,
    p_delivery_method text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_slot_time time;
    v_open_time time;
    v_close_time time;
    v_slot_duration interval := '30 minutes';
BEGIN
    SELECT (value->>'open')::time, (value->>'close')::time
    INTO v_open_time, v_close_time
    FROM shop_config WHERE key = 'shop_hours';
    
    v_slot_time := v_open_time;
    
    WHILE v_slot_time < v_close_time LOOP
        INSERT INTO order_slots (slot_date, slot_time, delivery_method, max_orders)
        VALUES (p_date, v_slot_time, p_delivery_method, 20)
        ON CONFLICT (slot_date, slot_time, delivery_method) DO NOTHING;
        
        v_slot_time := v_slot_time + v_slot_duration;
    END LOOP;
END;
$$;

-- RLS
ALTER TABLE public.order_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "order_slots_select_all" ON public.order_slots FOR SELECT USING (true);
CREATE POLICY "order_slots_update_admin" ON public.order_slots FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Add slot reference to orders
ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS slot_id bigint REFERENCES public.order_slots(id);

-- ============================================================
-- SECTION 6: INVENTORY MANAGEMENT
-- ============================================================
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL,
    unit            text NOT NULL DEFAULT 'กรัม',
    current_stock   numeric NOT NULL DEFAULT 0,
    min_stock       numeric NOT NULL DEFAULT 10,
    max_stock       numeric,
    reorder_point   numeric DEFAULT 20,
    cost_per_unit   numeric DEFAULT 0,
    supplier_info   jsonb,
    is_active       boolean DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Link menu items to inventory (many-to-many)
CREATE TABLE IF NOT EXISTS public.menu_item_ingredients (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id    bigint NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
    inventory_id    bigint NOT NULL REFERENCES public.inventory_items(id) ON DELETE CASCADE,
    quantity_used   numeric NOT NULL DEFAULT 1,
    is_required     boolean DEFAULT true,
    UNIQUE(menu_item_id, inventory_id)
);

-- Inventory transactions log
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id    bigint NOT NULL REFERENCES public.inventory_items(id),
    type            text NOT NULL CHECK (type IN ('in', 'out', 'adjust', 'waste')),
    quantity        numeric NOT NULL,
    reason          text,
    order_id        bigint REFERENCES public.orders(id),
    created_by      uuid REFERENCES auth.users(id),
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_menu_item_ingredients_menu ON public.menu_item_ingredients(menu_item_id);
CREATE INDEX IF NOT EXISTS idx_menu_item_ingredients_inventory ON public.menu_item_ingredients(inventory_id);
CREATE INDEX IF NOT EXISTS idx_inventory_transactions_inventory ON public.inventory_transactions(inventory_id);

-- RLS
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_item_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "inventory_select_all" ON public.inventory_items FOR SELECT USING (true);
CREATE POLICY "inventory_admin_all" ON public.inventory_items FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

CREATE POLICY "menu_item_ingredients_select_all" ON public.menu_item_ingredients FOR SELECT USING (true);
CREATE POLICY "menu_item_ingredients_admin_all" ON public.menu_item_ingredients FOR ALL USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

CREATE POLICY "inventory_transactions_select_admin" ON public.inventory_transactions FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);
CREATE POLICY "inventory_transactions_insert_admin" ON public.inventory_transactions FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- Function: Auto-update inventory when order is placed
CREATE OR REPLACE FUNCTION deduct_inventory_on_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_item record;
    v_ingredient record;
    v_total_used numeric;
BEGIN
    IF NEW.status IN ('confirmed', 'preparing') AND OLD.status = 'placed' THEN
        FOR v_item IN SELECT * FROM jsonb_to_recordset(NEW.items) AS x(menu_item_id bigint, quantity int)
        LOOP
            FOR v_ingredient IN 
                SELECT i.*, mi.quantity_used 
                FROM menu_item_ingredients mi
                JOIN inventory_items i ON mi.inventory_id = i.id
                WHERE mi.menu_item_id = v_item.menu_item_id
            LOOP
                v_total_used := v_ingredient.quantity_used * v_item.quantity;
                
                UPDATE inventory_items 
                SET current_stock = current_stock - v_total_used,
                    updated_at = now()
                WHERE id = v_ingredient.id;
                
                INSERT INTO inventory_transactions (inventory_id, type, quantity, reason, order_id)
                VALUES (v_ingredient.id, 'out', v_total_used, 'Order #' || NEW.id, NEW.id);
            END LOOP;
        END LOOP;
    END IF;
    
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_deduct_inventory ON public.orders;
CREATE TRIGGER tr_deduct_inventory
    AFTER UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION deduct_inventory_on_order();

-- Function: Check and auto-disable menu when inventory is low
CREATE OR REPLACE FUNCTION check_low_inventory()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NEW.current_stock <= NEW.min_stock THEN
        UPDATE menu_items 
        SET is_available = false
        WHERE id IN (
            SELECT menu_item_id 
            FROM menu_item_ingredients 
            WHERE inventory_id = NEW.id AND is_required = true
        );
    END IF;
    
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_check_low_inventory ON public.inventory_items;
CREATE TRIGGER tr_check_low_inventory
    AFTER UPDATE ON public.inventory_items
    FOR EACH ROW
    WHEN (OLD.current_stock > NEW.min_stock AND NEW.current_stock <= NEW.min_stock)
    EXECUTE FUNCTION check_low_inventory();

-- ============================================================
-- SECTION 7: PUSH NOTIFICATION TOKENS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.push_tokens (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    token           text NOT NULL,
    platform        text NOT NULL CHECK (platform IN ('web', 'ios', 'android')),
    is_active       boolean DEFAULT true,
    last_used       timestamptz DEFAULT now(),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON public.push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_push_tokens_active ON public.push_tokens(is_active);

ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "push_tokens_select_own" ON public.push_tokens FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "push_tokens_insert_own" ON public.push_tokens FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "push_tokens_delete_own" ON public.push_tokens FOR DELETE USING (auth.uid() = user_id);

-- ============================================================
-- SECTION 8: NOTIFICATION LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notifications (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    type            text NOT NULL,
    title           text NOT NULL,
    message         text NOT NULL,
    data            jsonb,
    is_read         boolean DEFAULT false,
    read_at         timestamptz,
    sent_via        text[] DEFAULT '{}',
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(user_id, is_read);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notifications_select_own" ON public.notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "notifications_update_own" ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

-- ============================================================
-- SECTION 9: BACKUP METADATA
-- ============================================================
CREATE TABLE IF NOT EXISTS public.backup_logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_type     text NOT NULL,
    status          text NOT NULL,
    file_path       text,
    file_size       bigint,
    record_count    jsonb,
    started_at      timestamptz NOT NULL DEFAULT now(),
    completed_at    timestamptz,
    error_message   text,
    created_by      uuid REFERENCES auth.users(id)
);

ALTER TABLE public.backup_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "backup_logs_admin" ON public.backup_logs FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true)
);

-- ============================================================
-- SECTION 10: HELPER FUNCTIONS
-- ============================================================

-- Function: Validate and apply coupon
CREATE OR REPLACE FUNCTION validate_and_apply_coupon(
    p_coupon_code text,
    p_user_id uuid,
    p_order_total numeric,
    p_menu_item_ids bigint[]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_coupon record;
    v_usage_count int;
    v_discount numeric;
BEGIN
    SELECT * INTO v_coupon
    FROM coupons
    WHERE code = UPPER(p_coupon_code)
    AND is_active = true
    AND (expires_at IS NULL OR expires_at > now());
    
    IF NOT FOUND THEN
        RETURN jsonb_build_object('valid', false, 'message', 'ไม่พบคูปองนี้');
    END IF;
    
    IF p_order_total < v_coupon.min_order_amount THEN
        RETURN jsonb_build_object('valid', false, 'message', 'ยอดสั่งซื้อขั้นต่ำ ' || v_coupon.min_order_amount || ' บาท');
    END IF;
    
    IF v_coupon.usage_limit IS NOT NULL AND v_coupon.usage_count >= v_coupon.usage_limit THEN
        RETURN jsonb_build_object('valid', false, 'message', 'คูปองหมดแล้ว');
    END IF;
    
    SELECT COUNT(*) INTO v_usage_count
    FROM coupon_usages
    WHERE coupon_id = v_coupon.id AND user_id = p_user_id;
    
    IF v_usage_count >= v_coupon.per_user_limit THEN
        RETURN jsonb_build_object('valid', false, 'message', 'คุณใช้คูปองนี้ครบกำหนดแล้ว');
    END IF;
    
    IF v_coupon.discount_type = 'fixed' THEN
        v_discount := v_coupon.discount_value;
    ELSIF v_coupon.discount_type = 'percentage' THEN
        v_discount := (p_order_total * v_coupon.discount_value / 100);
        IF v_coupon.max_discount IS NOT NULL THEN
            v_discount := LEAST(v_discount, v_coupon.max_discount);
        END IF;
    ELSE
        v_discount := 0;
    END IF;
    
    RETURN jsonb_build_object(
        'valid', true,
        'coupon_id', v_coupon.id,
        'discount', v_discount,
        'name', v_coupon.name
    );
END;
$$;

-- Function: Check if shop is open
CREATE OR REPLACE FUNCTION is_shop_open()
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_config jsonb;
    v_now time;
    v_today int;
BEGIN
    SELECT value INTO v_config FROM shop_config WHERE key = 'shop_hours';
    v_now := current_time;
    v_today := EXTRACT(DOW FROM current_date);
    
    IF NOT (v_today = ANY(ARRAY(SELECT jsonb_array_elements_text(v_config->'days_open')::int))) THEN
        RETURN false;
    END IF;
    
    IF v_now < (v_config->>'open')::time OR v_now > (v_config->>'close')::time THEN
        RETURN false;
    END IF;
    
    RETURN true;
END;
$$;

-- Function: Get available slots
CREATE OR REPLACE FUNCTION get_available_slots(
    p_date date,
    p_delivery_method text
)
RETURNS TABLE (
    slot_time time,
    available int,
    max_orders int
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    PERFORM generate_order_slots(p_date, p_delivery_method);
    
    RETURN QUERY
    SELECT 
        s.slot_time,
        (s.max_orders - s.current_orders) as available,
        s.max_orders
    FROM order_slots s
    WHERE s.slot_date = p_date
    AND s.delivery_method = p_delivery_method
    AND s.is_locked = false
    AND s.slot_time > current_time
    ORDER BY s.slot_time;
END;
$$;

-- ============================================================
-- SECTION 11: SEED DATA
-- ============================================================

INSERT INTO public.inventory_items (name, unit, current_stock, min_stock) VALUES
('หมูสับ', 'กรัม', 5000, 500),
('หมูกรอบ', 'กรัม', 3000, 300),
('ไก่', 'กรัม', 4000, 400),
('กุ้ง', 'กรัม', 2000, 200),
('ใบกะเพรา', 'กรัม', 1500, 150),
('ข้าวสวย', 'กรัม', 10000, 1000),
('ไข่ไก่', 'ฟอง', 100, 10),
('พริก', 'กรัม', 800, 80),
('กระเทียม', 'กรัม', 500, 50)
ON CONFLICT DO NOTHING;
