-- ============================================================
-- KAPRAO52 — อัปเดตเมนูตามความต้องการล่าสุด (MENU OVERHAUL V4 - เลือกระบุเนื้อสัตว์เฉพาะเมนูที่กำหนด)
-- อัปเดต: ชื่อเมนู, ราคา, คำอธิบาย, หมวดหมู่, รูปภาพ, และตัวเลือกเสริม (Options)
-- วิธีใช้: วาง SQL นี้ใน Supabase SQL Editor แล้วกด Run
-- ============================================================

INSERT INTO public.menu_items (
    id, name, description, price, category, image_url, 
    is_recommended, is_available, requires_meat, options
) 
OVERRIDING SYSTEM VALUE
VALUES 
    -- 🥘 พริกแกง
    (1, 'ผัดพริกแกง', 'เลือกระดับความเผ็ดและเนื้อสัตว์ได้', 50, 'curry', '/images/prik-kang-moo-chin.jpg', true, true, true, '[{"id":"meat_sap","name":"หมูสับ","price":0,"category":"meat"},{"id":"meat_sanko","name":"หมูสันคอสไลด์","price":0,"category":"meat"},{"id":"meat_kai","name":"ไก่","price":0,"category":"meat"},{"id":"meat_kai_sap","name":"ไก่สับ","price":0,"category":"meat"},{"id":"meat_krob","name":"หมูกรอบ","price":15,"category":"meat"},{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (2, 'ผัดพริกแกงกุ้ง', 'กุ้งเด้งๆ ผัดพริกแกงหอมๆ', 60, 'curry', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),

    -- 🌶️ กะเพรา
    (3, 'กะเพรากุ้ง', 'กุ้งสดตัวใหญ่ ผัดกะเพราพริกสด', 60, 'kaprao', '/images/kaprao-kung.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (4, 'กะเพราหมูสับ', 'เมนูยอดฮิตตลอดกาล', 50, 'kaprao', '/images/kaprao-moo-sap.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (5, 'กะเพราหมูเด้ง', 'หมูเด้งเนื้อหนึบกรอบ', 50, 'kaprao', '/images/kaprao-moo-deng.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (6, 'กะเพราสันคอสไลด์', 'สันคอสไลด์บางๆ นุ่มละมุน', 50, 'kaprao', '/images/kaprao-san-ko.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (7, 'กะเพราหมูสับไข่เยี่ยวม้า', 'หมูสับไข่เยี่ยวม้ากรอบๆ', 60, 'kaprao', '/images/kaprao-kai-yiao-ma.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (8, 'กะเพราหมูกรอบ', 'หมูกรอบเนื้อแน่น', 65, 'kaprao', '/images/kaprao-moo-krob.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),

    -- 🍜 เส้น
    (9, 'กะเพราวุ้นเส้น', 'วุ้นเส้นเหนียวนุ่ม ผัดเข้าเนื้อ', 55, 'noodle', NULL, false, true, true, '[{"id":"meat_sap","name":"หมูสับ","price":0,"category":"meat"},{"id":"meat_sanko","name":"หมูสันคอสไลด์","price":0,"category":"meat"},{"id":"meat_kai","name":"ไก่","price":0,"category":"meat"},{"id":"meat_kai_sap","name":"ไก่สับ","price":0,"category":"meat"},{"id":"meat_krob","name":"หมูกรอบ","price":15,"category":"meat"},{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (10, 'กะเพราวุ้นเส้นกุ้ง', 'วุ้นเส้นผัดกะเพรา ใส่กุ้งสด', 65, 'noodle', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (11, 'มาม่ากะเพรา', 'มาม่าเส้นหนึบ ผัดกะเพราแห้ง', 50, 'noodle', '/images/mama-pad-kaprao.jpg', true, true, true, '[{"id":"meat_sap","name":"หมูสับ","price":0,"category":"meat"},{"id":"meat_sanko","name":"หมูสันคอสไลด์","price":0,"category":"meat"},{"id":"meat_kai","name":"ไก่","price":0,"category":"meat"},{"id":"meat_kai_sap","name":"ไก่สับ","price":0,"category":"meat"},{"id":"meat_krob","name":"หมูกรอบ","price":15,"category":"meat"},{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (12, 'มาม่ากะเพรากุ้ง', 'มาม่ากะเพรา ใส่กุ้งเด้ง', 60, 'noodle', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),

    -- 🎋 หน่อไม้
    (13, 'กะเพราหน่อไม้', 'กะเพราใส่หน่อไม้ รสชาติจัดจ้าน', 55, 'bamboo', '/images/kaprao-nor-mai.jpg', false, true, true, '[{"id":"meat_sap","name":"หมูสับ","price":0,"category":"meat"},{"id":"meat_sanko","name":"หมูสันคอสไลด์","price":0,"category":"meat"},{"id":"meat_kai","name":"ไก่","price":0,"category":"meat"},{"id":"meat_kai_sap","name":"ไก่สับ","price":0,"category":"meat"},{"id":"meat_krob","name":"หมูกรอบ","price":15,"category":"meat"},{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (14, 'กะเพราหน่อไม้กุ้ง', 'กะเพราหน่อไม้ ใส่กุ้งตัวโต', 65, 'bamboo', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),

    -- 🧄 กระเทียม
    (15, 'กุ้งทอดกระเทียม', 'กุ้งทอดกระเทียมหอมๆ', 60, 'garlic', '/images/kung-kra-thiam.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไขเจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (16, 'หมูสับกระเทียม', 'หมูสับรวนกระเทียมพริกไทย', 50, 'garlic', '/images/moo-sap-kra-thiam.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (17, 'สันคอกระเทียม', 'สันคอหมูนุ่ม ผัดกระเทียม', 50, 'garlic', '/images/san-ko-kra-thiam.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (18, 'หมูเด้งกระเทียม', 'หมูเด้งหนึบ ผัดกระเทียม', 50, 'garlic', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),

    -- 🍛 อื่นๆ
    (19, 'ข้าวผัด', 'ข้าวผัดหอมกรุ่นกระทะ', 60, 'others', '/images/khao-pad-moo-chin.jpg', true, true, true, '[{"id":"meat_sap","name":"หมูสับ","price":0,"category":"meat"},{"id":"meat_sanko","name":"หมูสันคอสไลด์","price":0,"category":"meat"},{"id":"meat_kai","name":"ไก่","price":0,"category":"meat"},{"id":"meat_kai_sap","name":"ไก่สับ","price":0,"category":"meat"},{"id":"meat_krob","name":"หมูกรอบ","price":15,"category":"meat"},{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (20, 'ข้าวผัดกุ้ง', 'ข้าวผัดทะเลกุ้งเน้นๆ', 65, 'others', NULL, false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (21, 'ข้าวไข่ข้นน้ำพริกเผา', 'ไข่ 2 ฟอง นุ่มลื่น ราดน้ำพริกเผา', 40, 'others', NULL, true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (22, 'ข้าวไข่ข้น', 'ไข่ 2 ฟอง นุ่มลื่น ละลายในปาก', 40, 'others', '/images/khai-khon.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (23, 'กุ้งราดซอสมะขาม', 'กุ้งทอดซอสมะขามเปรี้ยวหวาน', 65, 'others', '/images/kung-rod-sot-makham.jpg', true, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb),
    (24, 'ไข่ดาวราดซอสมะขาม', 'ไข่ดาวทอดกรอบ ราดซอสมะขาม', 50, 'others', '/images/khai-dao-rod-sot-makham.jpg', false, true, false, '[{"id":"extra_rice","name":"พิเศษ ข้าว","price":10,"category":"extra"},{"id":"extra_meat","name":"พิเศษ เนื้อสัตว์","price":15,"category":"extra"},{"id":"egg_khon","name":"ไข่ข้น","price":10,"category":"egg"},{"id":"egg_dao","name":"ไข่ดาว","price":10,"category":"egg"},{"id":"egg_jiao","name":"ไข่เจียว","price":10,"category":"egg"},{"id":"egg_yiao_ma","name":"ไข่เยี่ยวม้า","price":15,"category":"egg"},{"id":"egg_tom","name":"ไข่ต้ม","price":10,"category":"egg"}]'::jsonb)

ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    category = EXCLUDED.category,
    image_url = EXCLUDED.image_url,
    is_recommended = EXCLUDED.is_recommended,
    is_available = EXCLUDED.is_available,
    requires_meat = EXCLUDED.requires_meat,
    options = EXCLUDED.options;

DELETE FROM public.menu_items WHERE id > 24;
