-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text,
  avatar_url text,
  display_name text
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Create orders table
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  items jsonb,
  total_price numeric,
  status text default 'cart', -- 'cart', 'pending', 'completed', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS on orders
alter table public.orders enable row level security;

create policy "Users can view their own orders" on public.orders
  for select using (auth.uid() = user_id);

create policy "Users can insert their own orders" on public.orders
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own orders" on public.orders
  for update using (auth.uid() = user_id);

create policy "Admins can view all orders" on public.orders
    for select using (auth.role() = 'service_role'); 
    -- Note: This is just an example, usually you'd have an 'is_admin' column in profiles
