-- =============================================
-- Kaprao52 App - Full Database Migration
-- Run this in Supabase SQL Editor
-- =============================================

-- =============================================
-- 1. PROFILES TABLE - Add missing columns
-- =============================================

ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS points int DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_orders int DEFAULT 0,
ADD COLUMN IF NOT EXISTS tier text DEFAULT 'MEMBER',
ADD COLUMN IF NOT EXISTS line_user_id text UNIQUE,
ADD COLUMN IF NOT EXISTS display_name text;

-- Index for LINE User ID lookup
CREATE INDEX IF NOT EXISTS idx_profiles_line_user_id ON public.profiles(line_user_id);

ALTER TABLE public.profiles enable row level security;

-- Allow users to insert their own profile
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" on public.profiles
    for insert with check (auth.uid() = id);

-- Allow users to update their own profile
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" on public.profiles
    for update using (auth.uid() = id);

-- Allow users to view their own profile
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile" on public.profiles
    for select using (auth.uid() = id);

-- Allow anyone to view profiles (for admin)
DROP POLICY IF EXISTS "Anyone can view all profiles" ON public.profiles;
CREATE POLICY "Anyone can view all profiles" on public.profiles
    for select using (true);

-- =============================================
-- 2. ORDERS TABLE - Add missing columns
-- =============================================

ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS customer_name text,
ADD COLUMN IF NOT EXISTS payment_method text DEFAULT 'cod',
ADD COLUMN IF NOT EXISTS payment_status text DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS subtotal_price numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_amount numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS discount_code text,
ADD COLUMN IF NOT EXISTS points_redeemed int DEFAULT 0,
ADD COLUMN IF NOT EXISTS points_earned int DEFAULT 0,
ADD COLUMN IF NOT EXISTS line_user_id text,
ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT timezone('utc'::text, now());

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_line_user_id ON public.orders(line_user_id);

-- =============================================
-- 3. LOTTO POOL TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.lotto_pool (
    id bigint generated by default as identity primary key,
    order_id bigint references public.orders(id),
    user_id uuid references auth.users,
    number text not null,
    draw_date date not null,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.lotto_pool enable row level security;

-- Allow anyone to view lotto pool
DROP POLICY IF EXISTS "Anyone can view lotto pool" ON public.lotto_pool;
CREATE POLICY "Anyone can view lotto pool" on public.lotto_pool
    for select using (true);

-- Allow users to insert their own lotto numbers
DROP POLICY IF EXISTS "Users can insert their own lotto" ON public.lotto_pool;
CREATE POLICY "Users can insert their own lotto" on public.lotto_pool
    for insert with check (auth.uid() = user_id OR auth.role() IN ('authenticated', 'anon'));

DROP POLICY IF EXISTS "Users can view their own lotto numbers" ON public.lotto_pool;
CREATE POLICY "Users can view their own lotto numbers" on public.lotto_pool 
    for select using (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_lotto_pool_user_id ON public.lotto_pool(user_id);
CREATE INDEX IF NOT EXISTS idx_lotto_pool_draw_date ON public.lotto_pool(draw_date);

-- =============================================
-- 4. POINT LOGS TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.point_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    action text not null, -- EARN, REDEEM, BONUS, ADJUST
    amount int not null,
    order_id bigint,
    note text,
    balance_after int,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.point_logs enable row level security;

DROP POLICY IF EXISTS "Users can view their own point logs" ON public.point_logs;
CREATE POLICY "Users can view their own point logs" on public.point_logs 
    for select using (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_point_logs_user_id ON public.point_logs(user_id);

-- Allow authenticated users to insert point logs (for admin adjustments)
DROP POLICY IF EXISTS "Authenticated users can insert point logs" ON public.point_logs;
CREATE POLICY "Authenticated users can insert point logs" on public.point_logs
    for insert with check (auth.role() = 'authenticated');

-- =============================================
-- 5. LOTTO RESULTS TABLE
-- =============================================

CREATE TABLE IF NOT EXISTS public.lotto_results (
    draw_date date primary key,
    last2 text not null,
    first3 text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE public.lotto_results enable row level security;

DROP POLICY IF EXISTS "Anyone can view lotto results" ON public.lotto_results;
CREATE POLICY "Anyone can view lotto results" on public.lotto_results 
    for select using (true);

-- =============================================
-- 6. RLS POLICIES - Fix for orders
-- =============================================

-- Allow anonymous users to insert orders (for guest checkout)
-- This allows any authenticated or anonymous user to insert orders
DROP POLICY IF EXISTS "Users can insert their own orders" ON public.orders;
CREATE POLICY "Users can insert their own orders" on public.orders
    for insert with check (
        auth.uid() = user_id OR 
        (auth.role() IN ('authenticated', 'anon'))
    );

-- Allow users to view their own orders
DROP POLICY IF EXISTS "Users can view their own orders" ON public.orders;
CREATE POLICY "Users can view their own orders" on public.orders
    for select using (auth.uid() = user_id);

-- Allow users to update their own orders
DROP POLICY IF EXISTS "Users can update their own orders" ON public.orders;
CREATE POLICY "Users can update their own orders" on public.orders
    for update using (auth.uid() = user_id);

-- =============================================
-- 7. DATABASE FUNCTION: handle_order_placed
-- =============================================

CREATE OR REPLACE FUNCTION public.handle_order_placed()
RETURNS TRIGGER AS $$
DECLARE
    earned_points int := 0;
    lotto_num text;
    next_draw date;
    current_points int;
BEGIN
    -- Only run when status is 'placed' on INSERT or UPDATE from non-placed to placed
    IF NEW.status = 'placed' AND (TG_OP = 'INSERT' OR OLD.status != 'placed') THEN
        
        -- 1. Calculate Points (Floor(Total / 10) = 1 point per 10 baht)
        IF NEW.points_earned IS NOT NULL AND NEW.points_earned > 0 THEN
            earned_points := NEW.points_earned;
        ELSE
            earned_points := FLOOR(COALESCE(NEW.total_price, 0) / 10);
        END IF;
        
        -- 2. Update Wallet (Profiles) - only if user_id exists
        IF NEW.user_id IS NOT NULL THEN
            -- Deduct redeemed points first
            IF COALESCE(NEW.points_redeemed, 0) > 0 THEN
                UPDATE public.profiles 
                SET points = GREATEST(0, points - NEW.points_redeemed),
                    updated_at = now()
                WHERE id = NEW.user_id;
                
                -- Log redemption
                SELECT points INTO current_points FROM public.profiles WHERE id = NEW.user_id;
                INSERT INTO public.point_logs (user_id, action, amount, order_id, note, balance_after)
                VALUES (NEW.user_id, 'REDEEM', NEW.points_redeemed, NEW.id, 
                        'แลกส่วนลด Order: ' || NEW.id, current_points);
            END IF;
            
            -- Add earned points
            IF earned_points > 0 THEN
                UPDATE public.profiles 
                SET points = points + earned_points,
                    total_orders = total_orders + 1,
                    updated_at = now()
                WHERE id = NEW.user_id;
                
                -- Log earning
                SELECT points INTO current_points FROM public.profiles WHERE id = NEW.user_id;
                INSERT INTO public.point_logs (user_id, action, amount, order_id, note, balance_after)
                VALUES (NEW.user_id, 'EARN', earned_points, NEW.id, 
                        'สั่งอาหาร Order: ' || NEW.id, current_points);
            ELSE
                -- Still increment order count
                UPDATE public.profiles 
                SET total_orders = total_orders + 1,
                    updated_at = now()
                WHERE id = NEW.user_id;
            END IF;

            -- 3. Generate Lotto Ticket
            lotto_num := RIGHT(NEW.id::text, 2);
            IF LENGTH(lotto_num) < 2 THEN
                lotto_num := LPAD(lotto_num, 2, '0');
            END IF;
            
            -- Calculate Draw Date (1st or 16th)
            IF EXTRACT(DAY FROM now()) > 1 AND EXTRACT(DAY FROM now()) < 16 THEN
                 next_draw := make_date(EXTRACT(YEAR FROM now())::int, EXTRACT(MONTH FROM now())::int, 16);
            ELSIF EXTRACT(DAY FROM now()) >= 16 THEN
                 next_draw := (date_trunc('month', now()) + interval '1 month')::date;
            ELSE
                 next_draw := make_date(EXTRACT(YEAR FROM now())::int, EXTRACT(MONTH FROM now())::int, 1);
            END IF;

            -- Insert lotto ticket (avoid duplicates)
            INSERT INTO public.lotto_pool (order_id, user_id, number, draw_date)
            VALUES (NEW.id, NEW.user_id, lotto_num, next_draw)
            ON CONFLICT DO NOTHING;
        END IF;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Recreate triggers
DROP TRIGGER IF EXISTS on_order_placed ON public.orders;
CREATE TRIGGER on_order_placed
AFTER UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.handle_order_placed();

DROP TRIGGER IF EXISTS on_order_insert_placed ON public.orders;
CREATE TRIGGER on_order_insert_placed
AFTER INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.handle_order_placed();

-- =============================================
-- 8. RPC FUNCTION: update_user_points (for client-side calls)
-- =============================================

CREATE OR REPLACE FUNCTION public.update_user_points(
    p_user_id uuid,
    p_points_delta int,
    p_order_id bigint DEFAULT NULL
)
RETURNS int AS $$
DECLARE
    new_balance int;
BEGIN
    UPDATE public.profiles
    SET points = GREATEST(0, points + p_points_delta),
        updated_at = now()
    WHERE id = p_user_id
    RETURNING points INTO new_balance;
    
    RETURN COALESCE(new_balance, 0);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute to authenticated users
GRANT EXECUTE ON FUNCTION public.update_user_points TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_user_points TO anon;

-- =============================================
-- 9. ADMIN VIEW (Optional - skipped due to potential conflicts)
-- =============================================
-- View is not required as admin dashboard works directly with tables

-- =============================================
-- 10. ENSURE PROFILES EXIST FOR ALL AUTH USERS
-- =============================================

-- Function to auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, display_name, points, total_orders, tier, updated_at)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', 'ลูกค้า'),
        0,
        0,
        'MEMBER',
        now()
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();

-- =============================================
-- DONE! Run this SQL in Supabase SQL Editor
-- =============================================
