// This file would be auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id <project-id> --schema public > src/types/supabase.ts

type Json = unknown

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          line_user_id: string | null
          display_name: string | null
          picture_url: string | null
          points: number
          total_orders: number
          tier: string
          avatar: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          line_user_id?: string | null
          display_name?: string | null
          picture_url?: string | null
          points?: number
          total_orders?: number
          tier?: string
          avatar?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          line_user_id?: string | null
          display_name?: string | null
          picture_url?: string | null
          points?: number
          total_orders?: number
          tier?: string
          avatar?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      menu_items: {
        Row: {
          id: number
          name: string
          description: string | null
          price: number
          category: string
          image_url: string | null
          requires_meat: boolean
          is_recommended: boolean
          is_available: boolean
          created_at: string
        }
        Insert: {
          id?: number
          name: string
          description?: string | null
          price: number
          category: string
          image_url?: string | null
          requires_meat?: boolean
          is_recommended?: boolean
          is_available?: boolean
          created_at?: string
        }
        Update: {
          id?: number
          name?: string
          description?: string | null
          price?: number
          category?: string
          image_url?: string | null
          requires_meat?: boolean
          is_recommended?: boolean
          is_available?: boolean
          created_at?: string
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: number
          user_id: string | null
          line_user_id: string | null
          guest_id: string | null
          customer_name: string
          phone_number: string | null
          address: string | null
          delivery_method: string | null
          special_instructions: string | null
          items: Json
          status: string
          notes: string | null
          total_price: number
          subtotal_price: number
          discount_amount: number
          discount_code: string | null
          points_redeemed: number
          points_earned: number
          payment_method: string
          payment_status: string
          payment_proof_url: string | null
          payment_verified: boolean
          payment_verified_at: string | null
          payment_verified_by: string | null
          payment_slip_data: Json | null
          payment_due_at: string | null
          queue_type: string | null
          queue_number: number | null
          queue_display: string | null
          estimated_minutes: number | null
          scheduled_for: string | null
          is_preorder: boolean
          guest_synced: boolean
          guest_synced_at: string | null
          tracking_token: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          user_id?: string | null
          line_user_id?: string | null
          guest_id?: string | null
          customer_name: string
          phone_number?: string | null
          address?: string | null
          delivery_method?: string | null
          special_instructions?: string | null
          items?: Json
          status?: string
          notes?: string | null
          total_price?: number
          subtotal_price?: number
          discount_amount?: number
          discount_code?: string | null
          points_redeemed?: number
          points_earned?: number
          payment_method?: string
          payment_status?: string
          payment_proof_url?: string | null
          payment_verified?: boolean
          payment_verified_at?: string | null
          payment_verified_by?: string | null
          payment_slip_data?: Json | null
          payment_due_at?: string | null
          queue_type?: string | null
          queue_number?: number | null
          queue_display?: string | null
          estimated_minutes?: number | null
          scheduled_for?: string | null
          is_preorder?: boolean
          guest_synced?: boolean
          guest_synced_at?: string | null
          tracking_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          user_id?: string | null
          line_user_id?: string | null
          guest_id?: string | null
          customer_name?: string
          phone_number?: string | null
          address?: string | null
          delivery_method?: string | null
          special_instructions?: string | null
          items?: Json
          status?: string
          notes?: string | null
          total_price?: number
          subtotal_price?: number
          discount_amount?: number
          discount_code?: string | null
          points_redeemed?: number
          points_earned?: number
          payment_method?: string
          payment_status?: string
          payment_proof_url?: string | null
          payment_verified?: boolean
          payment_verified_at?: string | null
          payment_verified_by?: string | null
          payment_slip_data?: Json | null
          payment_due_at?: string | null
          queue_type?: string | null
          queue_number?: number | null
          queue_display?: string | null
          estimated_minutes?: number | null
          scheduled_for?: string | null
          is_preorder?: boolean
          guest_synced?: boolean
          guest_synced_at?: string | null
          tracking_token?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      guest_identities: {
        Row: {
          id: string
          fingerprint: string | null
          display_name: string
          metadata: Json | null
          created_at: string
          last_active_at: string
        }
        Insert: {
          id?: string
          fingerprint?: string | null
          display_name?: string
          metadata?: Json | null
          created_at?: string
          last_active_at?: string
        }
        Update: {
          id?: string
          fingerprint?: string | null
          display_name?: string
          metadata?: Json | null
          created_at?: string
          last_active_at?: string
        }
        Relationships: []
      }
      lotto_tickets: {
        Row: {
          id: number
          order_id: number | null
          user_id: string | null
          guest_id: string | null
          number: string
          number_type: string
          source: string
          purchase_price: number
          draw_date: string
          status: string
          prize_type: string | null
          prize_amount: number
          prize_claimed: boolean
          prize_claimed_at: string | null
          notification_sent: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          order_id?: number | null
          user_id?: string | null
          guest_id?: string | null
          number: string
          number_type?: string
          source?: string
          purchase_price?: number
          draw_date: string
          status?: string
          prize_type?: string | null
          prize_amount?: number
          prize_claimed?: boolean
          prize_claimed_at?: string | null
          notification_sent?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          order_id?: number | null
          user_id?: string | null
          guest_id?: string | null
          number?: string
          number_type?: string
          source?: string
          purchase_price?: number
          draw_date?: string
          status?: string
          prize_type?: string | null
          prize_amount?: number
          prize_claimed?: boolean
          prize_claimed_at?: string | null
          notification_sent?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      lotto_pool: {
        Row: {
          id: number
          order_id: number
          user_id: string
          number: string
          draw_date: string
          created_at: string
        }
        Insert: {
          id?: number
          order_id: number
          user_id: string
          number: string
          draw_date: string
          created_at?: string
        }
        Update: {
          id?: number
          order_id?: number
          user_id?: string
          number?: string
          draw_date?: string
          created_at?: string
        }
        Relationships: []
      }
      lotto_results: {
        Row: {
          draw_date: string
          last2: string
          first3: string[]
          first_prize: string | null
          last3_digits: string[] | null
          source: string
          verified: boolean
          created_at: string
        }
        Insert: {
          draw_date: string
          last2: string
          first3?: string[]
          first_prize?: string | null
          last3_digits?: string[] | null
          source?: string
          verified?: boolean
          created_at?: string
        }
        Update: {
          draw_date?: string
          last2?: string
          first3?: string[]
          first_prize?: string | null
          last3_digits?: string[] | null
          source?: string
          verified?: string
          created_at?: string
        }
        Relationships: []
      }
      point_logs: {
        Row: {
          id: number
          user_id: string
          action: string
          amount: number
          order_id: number | null
          note: string | null
          balance_after: number
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          action: string
          amount: number
          order_id?: number | null
          note?: string | null
          balance_after: number
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          action?: string
          amount?: number
          order_id?: number | null
          note?: string | null
          balance_after?: number
          created_at?: string
        }
        Relationships: []
      }
      shop_config: {
        Row: {
          key: string
          value: Json
          updated_at: string
        }
        Insert: {
          key: string
          value: Json
          updated_at?: string
        }
        Update: {
          key?: string
          value?: Json
          updated_at?: string
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: number
          order_id: number
          user_id: string
          rating: number
          comment: string | null
          images: string[]
          would_recommend: boolean
          menu_item_ids: number[]
          is_approved: boolean
          reply: string | null
          replied_at: string | null
          replied_by: string | null
          helpful_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          order_id: number
          user_id?: string
          rating: number
          comment?: string | null
          images?: string[]
          would_recommend?: boolean
          menu_item_ids?: number[]
          is_approved?: boolean
          reply?: string | null
          replied_at?: string | null
          replied_by?: string | null
          helpful_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          order_id?: number
          user_id?: string
          rating?: number
          comment?: string | null
          images?: string[]
          would_recommend?: boolean
          menu_item_ids?: number[]
          is_approved?: boolean
          reply?: string | null
          replied_at?: string | null
          replied_by?: string | null
          helpful_count?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      review_votes: {
        Row: {
          review_id: number
          user_id: string
          created_at: string
        }
        Insert: {
          review_id: number
          user_id: string
          created_at?: string
        }
        Update: {
          review_id?: number
          user_id?: string
          created_at?: string
        }
        Relationships: []
      }
      inventory_items: {
        Row: {
          id: number
          name: string
          unit: string
          current_stock: number
          min_stock: number
          reorder_point: number
          cost_per_unit: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          name: string
          unit: string
          current_stock?: number
          min_stock?: number
          reorder_point?: number
          cost_per_unit?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          name?: string
          unit?: string
          current_stock?: number
          min_stock?: number
          reorder_point?: number
          cost_per_unit?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      inventory_transactions: {
        Row: {
          id: number
          inventory_id: number
          type: string
          quantity: number
          reason: string | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: number
          inventory_id: number
          type: string
          quantity: number
          reason?: string | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          inventory_id?: number
          type?: string
          quantity?: number
          reason?: string | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      menu_item_ingredients: {
        Row: {
          id: number
          menu_item_id: number
          inventory_id: number
          quantity_used: number
          is_required: boolean
          unit: string
          created_at: string
        }
        Insert: {
          id?: number
          menu_item_id: number
          inventory_id: number
          quantity_used?: number
          is_required?: boolean
          unit: string
          created_at?: string
        }
        Update: {
          id?: number
          menu_item_id?: number
          inventory_id?: number
          quantity_used?: number
          is_required?: boolean
          unit?: string
          created_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: number
          user_id: string
          type: string
          title: string
          message: string
          data: Json | null
          sent_via: string[]
          is_read: boolean
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          type: string
          title: string
          message: string
          data?: Json | null
          sent_via?: string[]
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          type?: string
          title?: string
          message?: string
          data?: Json | null
          sent_via?: string[]
          is_read?: boolean
          read_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          id: number
          user_id: string
          token: string
          platform: string
          is_active: boolean
          last_used: string
          created_at: string
        }
        Insert: {
          id?: number
          user_id: string
          token: string
          platform: string
          is_active?: boolean
          last_used?: string
          created_at?: string
        }
        Update: {
          id?: number
          user_id?: string
          token?: string
          platform?: string
          is_active?: boolean
          last_used?: string
          created_at?: string
        }
        Relationships: []
      }
      order_cancellations: {
        Row: {
          id: number
          order_id: number
          reason: string
          cancelled_at: string
          cancelled_by: string | null
          created_at: string
        }
        Insert: {
          id?: number
          order_id: number
          reason: string
          cancelled_at: string
          cancelled_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          order_id?: number
          reason?: string
          cancelled_at?: string
          cancelled_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      coupons: {
        Row: {
          id: number
          code: string
          name: string
          description: string | null
          discount_type: 'fixed' | 'percentage' | 'free_delivery'
          discount_value: number
          min_order_amount: number
          max_discount: number | null
          usage_limit: number | null
          usage_count: number
          per_user_limit: number
          applicable_items: number[] | null
          excluded_items: number[] | null
          starts_at: string
          expires_at: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          code: string
          name: string
          description?: string | null
          discount_type?: 'fixed' | 'percentage' | 'free_delivery'
          discount_value?: number
          min_order_amount?: number
          max_discount?: number | null
          usage_limit?: number | null
          usage_count?: number
          per_user_limit?: number
          applicable_items?: number[] | null
          excluded_items?: number[] | null
          starts_at: string
          expires_at?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          code?: string
          name?: string
          description?: string | null
          discount_type?: 'fixed' | 'percentage' | 'free_delivery'
          discount_value?: number
          min_order_amount?: number
          max_discount?: number | null
          usage_limit?: number | null
          usage_count?: number
          per_user_limit?: number
          applicable_items?: number[] | null
          excluded_items?: number[] | null
          starts_at?: string
          expires_at?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      coupon_usages: {
        Row: {
          id: number
          coupon_id: number
          user_id: string | null
          order_id: number | null
          discount_amount: number
          created_at: string
        }
        Insert: {
          id?: number
          coupon_id: number
          user_id?: string | null
          order_id?: number | null
          discount_amount: number
          created_at?: string
        }
        Update: {
          id?: number
          coupon_id?: number
          user_id?: string | null
          order_id?: number | null
          discount_amount?: number
          created_at?: string
        }
        Relationships: []
      }
      global_options: {
        Row: {
          id: string
          name: string
          is_available: boolean
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          is_available?: boolean
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          is_available?: boolean
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_queue_number: {
        Args: {
          p_delivery_method: string
          p_is_preorder?: boolean
        }
        Returns: {
          out_queue_type: string
          out_queue_number: number
          out_queue_display: string
        }[]
      }
      get_queue_status: {
        Args: {
          p_order_id: number
        }
        Returns: {
          queue_display: string
          queue_type: string
          orders_ahead: number
          estimated_minutes: number
          status: string
        }
      }
      sync_guest_to_member: {
        Args: {
          p_guest_id: string
          p_user_id: string
        }
        Returns: {
          success: boolean
          orders_synced: number
          points_added: number
          tickets_transferred: number
        }
      }
      purchase_lotto_ticket: {
        Args: {
          p_user_id: string
          p_number: string
          p_draw_date: string
          p_price: number
        }
        Returns: {
          success: boolean
          ticket_id: number
          points_spent: number
          new_balance: number
        }
      }
      claim_guest_order: {
        Args: {
          p_order_id: number
          p_tracking_token: string
        }
        Returns: {
          success: boolean
          points_earned: number
          new_balance: number
        }
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Helper types for easier usage
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']

// Schema type for Supabase client
export type Schema = Database['public']
